### ISSUE TITLE
Input form

### ISSUE THREAD

**Issue by deeuu** [pln-fing-udelar/fast-krippendorff#1]
Hey, nice implementation.

How come the input data are counts and not the raw data (as with [this example](https://github.com/grrrr/krippendorff-alpha/blob/master/krippendorff_alpha.py#L116))?

In particular, can't the [coincidences within units](http://repository.upenn.edu/cgi/viewcontent.cgi?article=1043&context=asc_papers) be computed internally from the reliability data matrix?

Thanks

**Comment by bryant1410** [comment]
It depends on how you have your data. In my case, I had to transform the data to obtain a reliability data matrix, it was much more simple to have one row per unit with the total count.

But yes, it can be done internally. [The sample file](https://github.com/pln-fing-udelar/fast-krippendorff/blob/master/sample.py#L11) shows a way to do it.

I'll try to do it in the short term.

**Comment by deeuu** [comment]
Okay I misunderstood the argument to `alpha`; you work on counts as input (not the coincidence matrix).

It would still be cool if the counts were computed internally. Perhaps using pandas?
```python
frame = pd.DataFrame(
    {'A': [np.nan, np.nan, np.nan, np.nan, np.nan, 3, 4, 1, 2, 1, 1, 3, 3, np.nan, 3],
     'B': [1, np.nan, 2, 1, 3, 3, 4, 3, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
     'C': [np.nan, np.nan, 2, 1, 3, 4, 4, np.nan, 2, 1, 1, 3, 3, np.nan, 4]
     },
    index=np.arange(1, 16)
)
# done internally:
counts = (
    frame.stack().reset_index(level=0).
    groupby('level_0')[0].value_counts().
    unstack(fill_value=0).
    reindex(frame.index) # Omit if it's okay to exclude empty units
)
```
I **think** this would be the most flexible for working with different data types...let me know what you think

**Comment by bryant1410** [comment]
I updated it. Be careful that I changed the API.

I didn't use Pandas to be agnostic to it.

**Comment by deeuu** [comment]
Perfect! Thanks
