### ISSUE TITLE
Does the agreement metric support multi-label data

### ISSUE THREAD

**Issue by mxli417** [pln-fing-udelar/fast-krippendorff#10]
Dear maintainers, 

does your implementation of Krippendorff's Alpha support multi-label interrater (dis-) agreement? Looking at the sample.py provided with your implementation it looks like it does not. Could you clarify this? I would be very grateful! 

Many thanks!

**Comment by bryant1410** [comment]
Can't you measure each label independently?

**Comment by mxli417** [comment]
Sure, this would of course be possible. But, like I said, I was interested in the native multi-label capabilities of the metric. Sorry if that is too trivial a question, but I was confused if the metric does support this at all  - or only by using a work around, like you suggested. Nevertheless, I would like to thank you for your quick reply on the issue.

**Comment by bryant1410** [comment]
Oh, I see. You expected more like a NumPy approach to this. This is a good point. I'm gonna think about it later. Feel free to open PR, but if the solution it's too forced then I'm more inclined to not support it, because the API is pretty clean right now.

**Comment by mxli417** [comment]
Alright, I will check out if this is feasible to do in a reasonable amount of time. If I manage to create a viable solution, I will come back to you. In the meantime, I think we can close the issue.
