### ISSUE TITLE
Ordinal value seems off

### ISSUE THREAD

**Issue by vanatteveldt** [pln-fing-udelar/fast-krippendorff#4]
I noticed a difference between R's irr::kripp.alpha and your method for ordinal measurements. Running the example from Krippendorff's own 'how to', it looks like your method is different from the one described there.

Input data:
![image](https://user-images.githubusercontent.com/1736240/56770314-e9c01f80-67b3-11e9-9698-9add8b6108ad.png)

Output according to paper:
![image](https://user-images.githubusercontent.com/1736240/56770365-0e1bfc00-67b4-11e9-8573-189e024e2506.png)

In python:
```{py}
>>> x
array([[ 1.,  2.,  3.,  3.,  2.,  1.,  4.,  1.,  2., nan, nan, nan],
       [ 1.,  2.,  3.,  3.,  2.,  2.,  4.,  1.,  2.,  5., nan,  3.],
       [nan,  3.,  3.,  3.,  2.,  3.,  4.,  2.,  2.,  5.,  1., nan],
       [ 1.,  2.,  3.,  3.,  2.,  4.,  4.,  1.,  2.,  5.,  1., nan]])
>>> krippendorff.alpha(x, level_of_measurement='ordinal')
0.7892168035524817
```

[1] https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2016/07/fulltext.pdf

(and for reference in R:
```{r}
> x
  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
A    1    2    3    3    2    1    4    1    2    NA    NA    NA
B    1    2    3    3    2    2    4    1    2     5    NA     3
C   NA    3    3    3    2    3    4    2    2     5     1    NA
D    1    2    3    3    2    4    4    1    2     5     1    NA
> irr::kripp.alpha(x, method = "ordinal")
 Krippendorff's alpha

 Subjects = 12 
   Raters = 4 
    alpha = 0.815 
```

**Comment by bryant1410** [comment]
I'll look into it and get back.

**Comment by vanatteveldt** [comment]
That was fast! Thanks, looking forward. I had a quick look at the code but would need to understand the data a bit better before I can have a go.

**Comment by bryant1410** [comment]
Okay, it's fixed. Thanks for pointing this out!

**Comment by vanatteveldt** [comment]
Fantastic, thanks for the quick fix. I can confirm that it now produces the expected output for the example cases. Thanks!
